name: push workflow
on:
  push:
    branches:
      - master
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: pull updated strings
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd del-v5 && npm up && cd ~/del-v5-staging && npm up
          host: ${{ secrets.HOST }}
          username: cairo
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        env:
          CI: true
